create table "public"."clears" (
    "id" bigint generated by default as identity not null,
    "user_id" uuid not null,
    "raid_id" bigint not null,
    "cleared_at" timestamp with time zone not null default now(),
    "character_id" text not null
);


alter table "public"."clears" enable row level security;

create table "public"."raids" (
    "id" bigint generated by default as identity not null,
    "name" text not null,
    "difficulty" text not null,
    "step" smallint not null,
    "level" smallint not null,
    "gold" integer not null,
    "is_biweekly" boolean not null
);


alter table "public"."raids" enable row level security;

CREATE UNIQUE INDEX characters_id_key ON public.characters USING btree (id);

CREATE UNIQUE INDEX clears_character_id_key ON public.clears USING btree (character_id);

CREATE UNIQUE INDEX clears_pkey ON public.clears USING btree (user_id, id, raid_id, character_id);

CREATE UNIQUE INDEX raids_pkey ON public.raids USING btree (id);

alter table "public"."clears" add constraint "clears_pkey" PRIMARY KEY using index "clears_pkey";

alter table "public"."raids" add constraint "raids_pkey" PRIMARY KEY using index "raids_pkey";

alter table "public"."characters" add constraint "characters_id_key" UNIQUE using index "characters_id_key";

alter table "public"."clears" add constraint "clears_character_id_fkey" FOREIGN KEY (character_id) REFERENCES characters(id) ON DELETE CASCADE not valid;

alter table "public"."clears" validate constraint "clears_character_id_fkey";

alter table "public"."clears" add constraint "clears_character_id_key" UNIQUE using index "clears_character_id_key";

alter table "public"."clears" add constraint "clears_raid_id_fkey" FOREIGN KEY (raid_id) REFERENCES raids(id) ON DELETE CASCADE not valid;

alter table "public"."clears" validate constraint "clears_raid_id_fkey";

alter table "public"."clears" add constraint "clears_user_id_fkey" FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE not valid;

alter table "public"."clears" validate constraint "clears_user_id_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.trigger_return_null()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$begin
  return null;
end;$function$
;

create policy "자신의 ID에 해당되는 데이터만 삭제 가능"
on "public"."characters"
as permissive
for delete
to authenticated
using (((auth.uid() = user_id) AND (is_test_user() = false)));


create policy "모든 사람 읽기 가능"
on "public"."clears"
as permissive
for select
to public
using (true);


create policy "자신의 ID로만 생성 가능"
on "public"."clears"
as permissive
for insert
to authenticated
with check (((auth.uid() = user_id) AND (is_test_user() = false)));


create policy "자신의 ID에 해당되는 데이터만 삭제 가능"
on "public"."clears"
as permissive
for delete
to authenticated
using (((auth.uid() = user_id) AND (is_test_user() = false)));


create policy "자신의 ID에 해당되는 데이터만 수정 가능"
on "public"."clears"
as permissive
for update
to authenticated
using (((auth.uid() = user_id) AND (is_test_user() = false)))
with check ((auth.uid() = user_id));


create policy "모든 사람 읽기 가능"
on "public"."raids"
as permissive
for select
to public
using (true);



