alter table "public"."clears" drop constraint "clears_pkey";

drop index if exists "public"."clears_pkey";

create table "public"."raids" (
    "id" bigint generated by default as identity not null,
    "name" text not null,
    "difficulty" text not null,
    "step" smallint not null,
    "level" smallint not null,
    "gold" integer not null,
    "is_biweekly" boolean not null
);


alter table "public"."raids" enable row level security;

alter table "public"."clears" drop column "raid_difficulty";

alter table "public"."clears" drop column "raid_name";

alter table "public"."clears" drop column "raid_step";

alter table "public"."clears" add column "raid_id" bigint not null;

alter table "public"."clears" alter column "cleared_at" set default now();

alter table "public"."clears" alter column "cleared_at" set data type timestamp with time zone using "cleared_at"::timestamp with time zone;

alter table "public"."clears" alter column "id" drop default;

alter table "public"."clears" alter column "id" add generated by default as identity;

alter table "public"."clears" alter column "id" set data type bigint using "id"::bigint;

CREATE UNIQUE INDEX clears_character_id_key ON public.clears USING btree (character_id);

CREATE UNIQUE INDEX raids_pkey ON public.raids USING btree (id);

CREATE UNIQUE INDEX clears_pkey ON public.clears USING btree (user_id, id, raid_id, character_id);

alter table "public"."raids" add constraint "raids_pkey" PRIMARY KEY using index "raids_pkey";

alter table "public"."clears" add constraint "clears_pkey" PRIMARY KEY using index "clears_pkey";

alter table "public"."clears" add constraint "clears_character_id_key" UNIQUE using index "clears_character_id_key";

alter table "public"."clears" add constraint "clears_raid_id_fkey" FOREIGN KEY (raid_id) REFERENCES raids(id) ON DELETE CASCADE not valid;

alter table "public"."clears" validate constraint "clears_raid_id_fkey";

create policy "모든 사람 읽기 가능"
on "public"."raids"
as permissive
for select
to public
using (true);



